#!/usr/bin/env python3
"""
ONE-TIME BACKFILL — schema 1 -> 2
=================================
`data/feed.js` is an accumulating store: events collected before a schema
change keep their old shape forever, because merge_events() only refreshes
events still inside the current feed window. This migrates the ones already
on disk.

What it fills:

  relevance_score    from the old flat `score` field (which is then removed)
  confidence_tier    from the event's source, then downgraded to
                     "unconfirmed" if the headline hedges
  opposition_status  for DELAY_REPORTED events, from the headline

Deliberately conservative: it only *adds* fields that are missing. Re-running
it is a no-op, so it is safe to run twice or to leave in a Makefile.

Note the ceiling on accuracy here. The collector derives these from headline
plus RSS summary; the persisted record keeps only the headline. Backfilled
values are therefore weaker than freshly collected ones — a story whose
hedging language sat in the summary rather than the headline will backfill as
trade_press. Everything collected from here on is derived properly.

Run:  python scripts/backfill_schema.py [--dry-run]
"""

import argparse, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ontology as O
from collect import has_term, opposition_status, confidence_of

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEED = os.path.join(ROOT, "data", "feed.js")

# Short code -> tier, straight from the source list, so this never drifts from
# what the live collector would assign.
SHORT_TIER = {s["short"]: s.get("tier", "trade_press") for s in O.SOURCES}

# Domain fallback for events whose source has since been removed from
# SOURCES (e.g. Data Center Planet, retired to MANUAL_SOURCES).
def tier_from_url(url):
    return "primary" if re.search(r"//(www\.)?sec\.gov/", url or "") else "trade_press"


def load():
    with open(FEED, encoding="utf-8") as f:
        raw = f.read()
    m = re.search(r"window\.DC_FEED\s*=\s*(\{.*\});\s*$", raw, re.S)
    if not m:
        sys.exit("Could not parse data/feed.js — is it the generated file?")
    return json.loads(m.group(1))


def write(payload):
    with open(FEED, "w", encoding="utf-8") as f:
        f.write("/* GENERATED by scripts/collect.py — do not edit by hand. */\n")
        f.write("window.DC_FEED = ")
        json.dump(payload, f, indent=1, ensure_ascii=False)
        f.write(";\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="report only, write nothing")
    a = ap.parse_args()

    payload = load()
    events = payload.get("events", [])
    counts = {"relevance_score": 0, "confidence_tier": 0, "opposition_status": 0,
              "score_removed": 0}
    tiers, statuses = {}, {}

    for ev in events:
        if ev.get("relevance_score") is None:
            ev["relevance_score"] = ev.get("score", 0)
            counts["relevance_score"] += 1
        if "score" in ev:
            del ev["score"]
            counts["score_removed"] += 1

        title = ev.get("title", "")

        if not ev.get("confidence_tier"):
            base = SHORT_TIER.get(ev.get("source"), tier_from_url(ev.get("url")))
            ev["confidence_tier"] = confidence_of(title, base)
            counts["confidence_tier"] += 1
        tiers[ev["confidence_tier"]] = tiers.get(ev["confidence_tier"], 0) + 1

        if "opposition_status" not in ev:
            ev["opposition_status"] = opposition_status(title, ev.get("event_type"))
            counts["opposition_status"] += 1
        if ev.get("opposition_status"):
            s = ev["opposition_status"]
            statuses[s] = statuses.get(s, 0) + 1

    payload["schema"] = 2

    print(f"events: {len(events)}")
    print(f"  relevance_score filled : {counts['relevance_score']}")
    print(f"  legacy `score` removed : {counts['score_removed']}")
    print(f"  confidence_tier filled : {counts['confidence_tier']}")
    print(f"  opposition_status set  : {counts['opposition_status']}")
    print(f"  confidence spread      : {tiers}")
    print(f"  opposition spread      : {statuses or '{}'}")

    if a.dry_run:
        print("\n--dry-run: nothing written.")
        return
    write(payload)
    print(f"\nwrote {FEED}")


if __name__ == "__main__":
    main()
